CAREERS_DATA = {
    "science": {
        "description": "Science opens doors to technology, research, engineering, and innovation-driven careers.",
        "careers": [
            {
                "name": "Software Engineer",
                "salary": "₹6–25 LPA",
                "growth": "High",
                "description": "Design, develop, and maintain software applications. Work with cutting-edge technologies to solve complex problems.",
                "skills": ["JavaScript", "Python", "System Design", "Data Structures", "Cloud Computing"],
                "companies": ["Google", "Microsoft", "Amazon", "Infosys", "TCS"],
                "education": "B.Tech/B.E. in CS/IT or MCA",
            },
            {
                "name": "Data Scientist",
                "salary": "₹8–30 LPA",
                "growth": "Very High",
                "description": "Analyze complex data to help organizations make better decisions using ML, statistics, and visualization.",
                "skills": ["Python", "Machine Learning", "Statistics", "SQL", "Deep Learning"],
                "companies": ["Amazon", "Flipkart", "Google", "Mu Sigma", "Tiger Analytics"],
                "education": "B.Tech + M.Tech/MS in Data Science or Statistics",
            },
            {
                "name": "AI/ML Engineer",
                "salary": "₹10–40 LPA",
                "growth": "Very High",
                "description": "Build intelligent systems and algorithms that can learn and make decisions. A rapidly growing field.",
                "skills": ["Deep Learning", "NLP", "TensorFlow", "PyTorch", "Computer Vision"],
                "companies": ["OpenAI", "Google DeepMind", "NVIDIA", "Meta", "Microsoft"],
                "education": "B.Tech + M.Tech/PhD in AI/ML",
            },
            {
                "name": "Mechanical Engineer",
                "salary": "₹4–15 LPA",
                "growth": "Moderate",
                "description": "Design and develop mechanical systems from automobiles to aerospace components.",
                "skills": ["CAD/CAM", "Thermodynamics", "Material Science", "FEA", "3D Printing"],
                "companies": ["Tata Motors", "L&T", "Mahindra", "Boeing", "ISRO"],
                "education": "B.Tech/B.E. in Mechanical Engineering",
            },
            {
                "name": "Research Scientist",
                "salary": "₹7–25 LPA",
                "growth": "High",
                "description": "Conduct cutting-edge research in physics, chemistry, biology, or interdisciplinary fields to advance human knowledge.",
                "skills": ["Research Methodology", "Data Analysis", "Lab Skills", "Scientific Writing", "Critical Thinking"],
                "companies": ["ISRO", "DRDO", "BARC", "IISc", "CSIR Labs"],
                "education": "M.Sc./PhD in relevant science field",
            },
        ],
    },
    "commerce": {
        "description": "Commerce streams lead to business, finance, management, and entrepreneurial opportunities.",
        "careers": [
            {
                "name": "Chartered Accountant",
                "salary": "₹7–30 LPA",
                "growth": "High",
                "description": "Handle financial auditing, taxation, and advisory services. One of the most sought-after professions in India.",
                "skills": ["Accounting", "Tax Law", "Auditing", "Financial Analysis", "GST"],
                "companies": ["Deloitte", "EY", "KPMG", "PwC", "BDO India"],
                "education": "CA Foundation + Inter + Final from ICAI",
            },
            {
                "name": "Investment Banker",
                "salary": "₹10–50 LPA",
                "growth": "High",
                "description": "Help companies raise capital, handle mergers and acquisitions, and provide strategic financial advisory.",
                "skills": ["Financial Modeling", "Valuation", "M&A Advisory", "Excel", "Bloomberg"],
                "companies": ["Goldman Sachs", "JP Morgan", "Morgan Stanley", "Kotak", "ICICI"],
                "education": "MBA Finance or CFA Certification",
            },
            {
                "name": "Financial Analyst",
                "salary": "₹5–18 LPA",
                "growth": "High",
                "description": "Analyze financial data and market trends to help businesses and individuals make investment decisions.",
                "skills": ["Excel", "Financial Modeling", "Data Analysis", "Accounting", "Forecasting"],
                "companies": ["HDFC", "SBI", "Bajaj Finance", "Citi", "Axis Bank"],
                "education": "B.Com/BBA + MBA/CFA",
            },
            {
                "name": "Business Manager",
                "salary": "₹8–25 LPA",
                "growth": "Moderate",
                "description": "Lead and manage business operations, teams, and strategy. Drive organizational growth and efficiency.",
                "skills": ["Leadership", "Strategic Planning", "Communication", "Project Management", "Analytics"],
                "companies": ["Hindustan Unilever", "P&G", "Amazon", "Reliance", "Tata Group"],
                "education": "BBA/B.Com + MBA",
            },
        ],
    },
    "arts": {
        "description": "Arts unleash creativity and communication, opening paths in design, media, writing, and performance.",
        "careers": [
            {
                "name": "UI/UX Designer",
                "salary": "₹5–20 LPA",
                "growth": "Very High",
                "description": "Design intuitive and beautiful user interfaces for apps and websites. Combine creativity with technology.",
                "skills": ["Figma", "Adobe XD", "User Research", "Prototyping", "Design Thinking"],
                "companies": ["Google", "Apple", "Swiggy", "Zomato", "Razorpay"],
                "education": "B.Des or any degree + UX Certification",
            },
            {
                "name": "Content Writer",
                "salary": "₹3–12 LPA",
                "growth": "High",
                "description": "Create compelling written content for websites, blogs, marketing, and social media platforms.",
                "skills": ["Writing", "SEO", "Research", "Storytelling", "Content Strategy"],
                "companies": ["Times Internet", "HubSpot", "Freshworks", "Unacademy", "Freelance"],
                "education": "BA in English/Journalism/Mass Communication",
            },
            {
                "name": "Journalist",
                "salary": "₹4–15 LPA",
                "growth": "Moderate",
                "description": "Investigate, report, and present news and stories. Work in print, digital, TV, or radio media.",
                "skills": ["Writing", "Research", "Interviewing", "Video Editing", "Critical Thinking"],
                "companies": ["NDTV", "Times of India", "Indian Express", "The Hindu", "Republic"],
                "education": "BA/MA in Journalism or Mass Communication",
            },
            {
                "name": "Graphic Designer",
                "salary": "₹3–15 LPA",
                "growth": "High",
                "description": "Create visual concepts using computer software to communicate ideas that inspire and inform consumers.",
                "skills": ["Photoshop", "Illustrator", "Typography", "Branding", "Motion Graphics"],
                "companies": ["Adobe", "Canva", "Ogilvy", "Wunderman", "Freelance"],
                "education": "B.Des/BFA or Self-taught + Portfolio",
            },
        ],
    },
    "medical": {
        "description": "Medical careers save lives and improve healthcare. Compassion meets science in this noble field.",
        "careers": [
            {
                "name": "Doctor (MBBS)",
                "salary": "₹8–30 LPA",
                "growth": "High",
                "description": "Diagnose and treat diseases, prescribe medications, and improve patient health. A highly respected profession.",
                "skills": ["Clinical Skills", "Diagnosis", "Patient Care", "Surgery", "Research"],
                "companies": ["AIIMS", "Apollo", "Fortis", "Max Healthcare", "Government Hospitals"],
                "education": "MBBS + MD/MS Specialization",
            },
            {
                "name": "Pharmacist",
                "salary": "₹3–12 LPA",
                "growth": "Moderate",
                "description": "Prepare and dispense medications, advise patients on drug usage, and ensure safe pharmaceutical practices.",
                "skills": ["Pharmacology", "Drug Interaction", "Patient Counseling", "Chemistry", "Regulatory"],
                "companies": ["Cipla", "Sun Pharma", "Dr. Reddy's", "Lupin", "Biocon"],
                "education": "B.Pharm/M.Pharm",
            },
            {
                "name": "Biotechnologist",
                "salary": "₹5–18 LPA",
                "growth": "High",
                "description": "Apply biology and technology to develop new products, improve crops, develop medicines, and solve environmental problems.",
                "skills": ["Molecular Biology", "Genetics", "Bioinformatics", "Lab Techniques", "Data Analysis"],
                "companies": ["Biocon", "Serum Institute", "Bharat Biotech", "Novartis", "Genentech"],
                "education": "B.Tech/M.Tech in Biotechnology",
            },
            {
                "name": "Medical Researcher",
                "salary": "₹6–20 LPA",
                "growth": "High",
                "description": "Conduct research to develop new treatments, drugs, and medical devices to fight diseases.",
                "skills": ["Research Methods", "Clinical Trials", "Biostatistics", "Lab Skills", "Scientific Writing"],
                "companies": ["ICMR", "WHO", "Pfizer", "AstraZeneca", "Govt Research Labs"],
                "education": "MBBS/MD + PhD or M.Sc + PhD",
            },
        ],
    },
    "architecture": {
        "description": "Architecture merges art, engineering, and sustainability to shape the built environment.",
        "careers": [
            {
                "name": "Architect",
                "salary": "₹5–20 LPA",
                "growth": "Moderate",
                "description": "Design buildings and spaces that are functional, safe, and aesthetically pleasing. Shape the skyline of cities.",
                "skills": ["AutoCAD", "Revit", "3D Modeling", "Sketching", "Structural Knowledge"],
                "companies": ["Hafeez Contractor", "CP Kukreja", "Morphogenesis", "RSP Architects", "Freelance"],
                "education": "B.Arch (5 years)",
            },
            {
                "name": "Urban Planner",
                "salary": "₹5–18 LPA",
                "growth": "High",
                "description": "Plan and design communities, transportation systems, and infrastructure for sustainable city development.",
                "skills": ["GIS", "Urban Design", "Policy", "Data Analysis", "Community Engagement"],
                "companies": ["TCPO", "Smart City Projects", "World Bank", "CEPT", "Municipal Corps"],
                "education": "B.Arch/B.Planning + M.Planning",
            },
            {
                "name": "Interior Designer",
                "salary": "₹4–15 LPA",
                "growth": "High",
                "description": "Design functional and beautiful interior spaces for homes, offices, and commercial buildings.",
                "skills": ["3ds Max", "SketchUp", "Material Knowledge", "Color Theory", "Space Planning"],
                "companies": ["Livspace", "HomeLane", "Godrej Interio", "Design Studios", "Freelance"],
                "education": "B.Des in Interior Design or B.Arch",
            },
        ],
    },
    "nursing": {
        "description": "Nursing is a rewarding healthcare career focused on patient care, empathy, and medical expertise.",
        "careers": [
            {
                "name": "Registered Nurse",
                "salary": "₹3–10 LPA",
                "growth": "High",
                "description": "Provide patient care in hospitals and clinics. Monitor health, administer medication, and support recovery.",
                "skills": ["Patient Care", "Clinical Skills", "Communication", "First Aid", "Record Keeping"],
                "companies": ["AIIMS", "Apollo", "Fortis", "Manipal Hospitals", "Government Hospitals"],
                "education": "B.Sc Nursing (4 years)",
            },
            {
                "name": "Healthcare Assistant",
                "salary": "₹2–6 LPA",
                "growth": "High",
                "description": "Assist healthcare professionals with patient care, record-keeping, and administrative tasks in medical settings.",
                "skills": ["Patient Support", "Basic Medical", "Communication", "Empathy", "Teamwork"],
                "companies": ["Hospitals", "Clinics", "Elderly Care", "Home Healthcare", "NGOs"],
                "education": "Diploma in Nursing or ANM",
            },
            {
                "name": "Nurse Practitioner",
                "salary": "₹6–18 LPA",
                "growth": "Very High",
                "description": "Advanced practice nurse who can diagnose illnesses, prescribe medications, and manage patient care independently.",
                "skills": ["Advanced Clinical", "Diagnosis", "Prescription", "Leadership", "Research"],
                "companies": ["Super Specialty Hospitals", "Private Practice", "International Hospitals"],
                "education": "M.Sc Nursing + NP Certification",
            },
        ],
    },
}
