SCHOLARSHIPS_DATA = [
    {
        "id": 1,
        "name": "PM Vidyalakshmi Scholarship",
        "provider": "Government of India",
        "amount": "₹75,000/year",
        "deadline": "March 31, 2026",
        "category": "government",
        "eligibility": "Students from families with annual income below ₹8 LPA",
        "description": "A comprehensive central government scholarship supporting meritorious students from economically weaker sections to pursue higher education in recognized institutions.",
        "appliedCount": 2500000,
        "link": "https://www.vidyalakshmi.co.in",
    },
    {
        "id": 2,
        "name": "INSPIRE Scholarship",
        "provider": "Dept. of Science & Technology",
        "amount": "₹80,000/year",
        "deadline": "April 15, 2026",
        "category": "merit",
        "eligibility": "Top 1% in Class 12 Board Exams pursuing B.Sc/M.Sc",
        "description": "Innovation in Science Pursuit for Inspired Research (INSPIRE) program to attract meritorious students to pursue science courses.",
        "appliedCount": 350000,
        "link": "https://online-inspire.gov.in",
    },
    {
        "id": 3,
        "name": "Post Matric Scholarship for SC/ST",
        "provider": "Ministry of Social Justice",
        "amount": "Full Tuition + ₹5,500/month",
        "deadline": "December 31, 2025",
        "category": "need",
        "eligibility": "SC/ST students with family income below ₹2.5 LPA",
        "description": "Financial assistance to SC/ST students studying at post-matriculation or post-secondary level to enable them to complete their education.",
        "appliedCount": 8000000,
        "link": "https://scholarships.gov.in",
    },
    {
        "id": 4,
        "name": "Kishore Vaigyanik Protsahan Yojana (KVPY)",
        "provider": "Dept. of Science & Technology",
        "amount": "₹5,000–7,000/month + Contingency",
        "deadline": "August 31, 2025",
        "category": "merit",
        "eligibility": "Students in Class 11/12 or 1st year of B.Sc in basic sciences",
        "description": "A prestigious national fellowship program in basic sciences to encourage students to take up research careers. Includes monthly stipend and annual contingency grant.",
        "appliedCount": 100000,
        "link": "https://kvpy.iisc.ac.in",
    },
    {
        "id": 5,
        "name": "Tata Trusts Scholarship",
        "provider": "Tata Trusts",
        "amount": "Up to ₹3,00,000/year",
        "deadline": "July 31, 2025",
        "category": "private",
        "eligibility": "Students enrolled in specific UG/PG programs with financial need",
        "description": "Need-based scholarship by Tata Group covering tuition fees, hostel charges, and living expenses for students at partner institutions.",
        "appliedCount": 50000,
        "link": "https://www.tatatrusts.org",
    },
    {
        "id": 6,
        "name": "AICTE Pragati Scholarship for Girls",
        "provider": "AICTE",
        "amount": "₹50,000/year",
        "deadline": "November 30, 2025",
        "category": "government",
        "eligibility": "Girl students in AICTE-approved technical institutions, family income <₹8 LPA",
        "description": "Scholarship to encourage girl students to pursue technical education in AICTE-approved colleges. Covers tuition, books, and equipment.",
        "appliedCount": 400000,
        "link": "https://www.aicte-india.org",
    },
    {
        "id": 7,
        "name": "NSP Central Sector Scholarship",
        "provider": "MHRD, Government of India",
        "amount": "₹10,000–20,000/year",
        "deadline": "October 31, 2025",
        "category": "government",
        "eligibility": "Students who scored above 80th percentile in Class 12",
        "description": "Central government scholarship for college and university students who have scored above the 80th percentile in their Class 12 board exams.",
        "appliedCount": 850000,
        "link": "https://scholarships.gov.in",
    },
    {
        "id": 8,
        "name": "Reliance Foundation UG Scholarship",
        "provider": "Reliance Foundation",
        "amount": "Up to ₹2,00,000/year",
        "deadline": "September 15, 2025",
        "category": "private",
        "eligibility": "Students in UG STEM programs with family income <₹15 LPA",
        "description": "Merit-cum-need based scholarship for Indian students pursuing undergraduate degrees in STEM fields from recognized institutions across India.",
        "appliedCount": 180000,
        "link": "https://www.reliancefoundation.org",
    },
    {
        "id": 9,
        "name": "NTSE Scholarship",
        "provider": "NCERT",
        "amount": "₹1,250–2,000/month",
        "deadline": "August 31, 2025",
        "category": "merit",
        "eligibility": "Students who qualify NTSE at national level",
        "description": "National Talent Search Examination scholarship for exceptionally talented students to pursue sciences and social sciences at undergraduate and postgraduate levels.",
        "appliedCount": 500000,
        "link": "https://www.ncert.nic.in",
    },
    {
        "id": 10,
        "name": "Minority Communities Scholarship",
        "provider": "Ministry of Minority Affairs",
        "amount": "Full Tuition + ₹10,000/year",
        "deadline": "October 15, 2025",
        "category": "need",
        "eligibility": "Students from notified minority communities with income <₹2 LPA",
        "description": "Scholarship for students belonging to minority communities to pursue professional and technical courses at undergraduate and postgraduate levels.",
        "appliedCount": 2000000,
        "link": "https://scholarships.gov.in",
    },
    {
        "id": 11,
        "name": "Infosys Foundation Scholarship",
        "provider": "Infosys Foundation",
        "amount": "Up to ₹1,50,000/year",
        "deadline": "June 30, 2025",
        "category": "private",
        "eligibility": "Engineering students from economically disadvantaged backgrounds",
        "description": "Financial support for meritorious students from disadvantaged backgrounds to complete their engineering education at recognized institutions.",
        "appliedCount": 30000,
        "link": "https://www.infosys.com/infosys-foundation",
    },
    {
        "id": 12,
        "name": "ISHAN UDAY Scholarship (NE Region)",
        "provider": "UGC",
        "amount": "₹5,400/month + ₹20,000 Contingency",
        "deadline": "November 30, 2025",
        "category": "government",
        "eligibility": "Students from NE states with family income <₹4.5 LPA",
        "description": "Special area scholarship for students from North Eastern states, designed to encourage young talent from the region to pursue higher education.",
        "appliedCount": 95000,
        "link": "https://www.ugc.ac.in",
    },
]
